### ISSUE TITLE
NOS Sport live streams

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1095]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1095) by michiel modderman (Bitbucket: [chielmi](https://bitbucket.org/chielmi), GitHub: [chielmi](https://github.com/chielmi)).**

----------------------------------------

Laat ik beginnen dat ik dit dé add-on voor Kodi vind. Ik ben al jaren een zeer tevreden gebruiker :-).

Zou het mogelijk zijn om ondersteuning voor de NOS Sport live streams toe te voegen? Het zijn de live streams die op deze pagina aan de rechter kant staan:
https://nos.nl/sport/

Ik heb het idee dat de url's vrij simpel zijn. Als ik via Yatse zo'n url probeer af te spelen (wat helaas faalt) dan kom ik op:
https://nos.nl/l/2268921
voor een live stream van vandaag. Deze url wordt vervolgens geresolved naar:
https://nos.nl/livestream/2268921-wb-veldrijden-hoogerheide-v.html

Het nummer van de url (2268921) lijkt bij elke volgende live stream 1 waarde op te lopen.

Denk je dat het mogelijk is om deze feature toe te voegen? Ik zou echt eeuwig dankbaar zijn ;-).

Keep up the good work!

**Comment by dagwieers** [comment]
Moet dit niet label "channel" krijgen?

**Comment by ltGuillaume** [comment]
Ik zou dit ook echt een heerlijke toevoeging vinden, grijp er erg vaak op mis.

**Comment by ltGuillaume** [comment]
Up until a few weeks ago, I could use the following playlist to open a few streams directly (in MPV). Since there's more expertise here regarding NOS API changes, perhaps rewriting these to the newer API could still do the trick. Or is this opportunity gone for good?

```
#EXTM3U8
#EXTINF:0,NPO1
http://ipv4.api.nos.nl/resolve.php/livestream?url=/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
#EXTINF:0,NPO2
http://ipv4.api.nos.nl/resolve.php/livestream?url=/live/npo/tvlive/npo2/npo2.isml/npo2.m3u8
#EXTINF:0,NPO3
http://ipv4.api.nos.nl/resolve.php/livestream?url=/live/npo/tvlive/npo3/npo3.isml/npo3.m3u8
#EXTINF:0,NOS Sport #1
http://ipv4.api.nos.nl/resolve.php/livestream?url=/live/npo/tvlive/mcr1/mcr1.isml/mcr1.m3u8
#EXTINF:0,NOS Sport #2
http://ipv4.api.nos.nl/resolve.php/livestream?url=/live/npo/tvlive/mcr2/mcr2.isml/mcr2.m3u8
#EXTINF:0,NOS Sport #3
http://ipv4.api.nos.nl/resolve.php/livestream?url=/live/npo/tvlive/mcr3/mcr3.isml/mcr3.m3u8
```

**Comment by basrieter** [comment]
Where are the streams located on the NOS site?

**Comment by ltGuillaume** [comment]
The sports live streams (what this issue is about) appear on https://nos.nl/uitzendingen as soon as they become available. Currently, there's no such stream, sorry. I'll post a message as soon as one becomes available.

As for the three other streams (NPO1, NPO2, NPO3), these links used to work fine (until a few weeks ago) for unencrypted streams of the respective channels.

**Comment by basrieter** [comment]
The NPO streams are also located in the NPO channel, so I won't be adding them here.

**Comment by ltGuillaume** [comment]
That makes sense, Of course. But I'm guessing these use tokens (and are probably encrypted, too?). That was so great about this playlist: unencrypted non-tokenized streams that could be opened in most video players. No idea if it would still work with a simple adjustment to make up for changes in the API address.

**Comment by ltGuillaume** [comment]
There's a stream on https://nos.nl/uitzendingen/ of a debate right now. Direct link https://nos.nl/livestream/2312284-kijk-hier-debat-met-minister-bijleveld-over-burgerdoden-in-hawija.html

**Comment by basrieter** [comment]
But that is NOS Politiek which is in the NPO channel.

**Comment by ltGuillaume** [comment]
Probably too late, but Studio Sport livestream at https://nos.nl/uitzendingen right now.

https://nos.nl/livestream/2312678-studio-sport.html

**Comment by basrieter** [comment]
Can somebody check https://nos.nl/s/dashboard.json whenever a live stream is running? The URL redirects but gives output in the IE/FF/Chrome Developer Tools.

**Comment by ltGuillaume** [comment]
The current live stream, NOS Studio Sport Eredivisie, is (probably) just NPO1?

I'm not getting any output in the developer tools, though. Response is empty.

**Comment by basrieter** [comment]
Yes, that is NPO1. The content should look like something like this:

```{"traffic":0,"weather":{"temperature":5,"symbol":"ms____"},"has_livestream":false}```

**Comment by ltGuillaume** [comment]
Now there's the UN Climate Convention livestream (https://nos.nl/livestream/2312952-kijk-hier-opening-vn-klimaattop-in-madrid.html), but the response of https://nos.nl/s/dashboard.json is `has_livestream : false`.

**Comment by basrieter** [comment]
Sorry, I was too busy in real life. Next time.

**Comment by ltGuillaume** [comment]
Haha, good on ya! 😁

**Comment by ltGuillaume** [comment]
Currently, the European Championship Swimming are streaming. https://nos.nl/s/dashboard.json again gives `has_livestream | false`.

https://smoote2f.omroep.nl/urishieldv2/l2fm266f433b3ae89f81005dea96e7000000.28601fb6c5d78dc8664614337735c148/live/nos/events/nos_event02/nos_event02.isml/nos_event02.m3u8:
```
#EXTM3U
#EXT-X-VERSION:1
## Created with Unified Streaming Platform(version=1.9.5)

# variants
#EXT-X-STREAM-INF:BANDWIDTH=558000,AVERAGE-BANDWIDTH=507000,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=480x270,FRAME-RATE=25,VIDEO-RANGE=SDR
nos_event02-audio_1=128000-video=349952.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=966000,AVERAGE-BANDWIDTH=878000,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=640x360,FRAME-RATE=25,VIDEO-RANGE=SDR
nos_event02-audio_1=128000-video=699968.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1432000,AVERAGE-BANDWIDTH=1302000,CODECS="mp4a.40.2,avc1.66.30",RESOLUTION=848x480,FRAME-RATE=25,VIDEO-RANGE=SDR
nos_event02-audio_1=128000-video=1099968.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1782000,AVERAGE-BANDWIDTH=1620000,CODECS="mp4a.40.2,avc1.77.31",RESOLUTION=960x540,FRAME-RATE=25,VIDEO-RANGE=SDR
nos_event02-audio_1=128000-video=1400000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=2482000,AVERAGE-BANDWIDTH=2256000,CODECS="mp4a.40.2,avc1.77.41",RESOLUTION=1280x720,FRAME-RATE=25,VIDEO-RANGE=SDR
nos_event02-audio_1=128000-video=2000000.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3065000,AVERAGE-BANDWIDTH=2786000,CODECS="mp4a.40.2,avc1.77.41",RESOLUTION=1920x1080,FRAME-RATE=25,VIDEO-RANGE=SDR
nos_event02-audio_1=128000-video=2499968.m3u8

# variants
#EXT-X-STREAM-INF:BANDWIDTH=150000,AVERAGE-BANDWIDTH=136000,CODECS="mp4a.40.2"
nos_event02-audio_1=128000.m3u8
```

**Comment by ltGuillaume** [comment]
Swimming stream until 2100h.

**Comment by basrieter** [comment]
Apparently I am just too late.

**Comment by ltGuillaume** [comment]
Well blimey, that you are 😢😊 Better luck next time! 😁

**Comment by ltGuillaume** [comment]
This afternoon at 2 until 6, there will be a Shorttrack stream. Tomorrow, same thing, same time.

**Comment by ltGuillaume** [comment]
Currently there are 3 sports streams online. Perhaps you could have a look?

**Comment by basrieter** [comment]
How is this issue at the moment? Still valid.

**Comment by ltGuillaume** [comment]
With the upcoming Olympics, definitely! I guess there will be quite a few streams then.

**Comment by rrmvanderlinden** [comment]
Indeed, still valid. In 2016 there was an addon for Rio. (Olympic livestreams NOS) Is it helpfull to post/provide the file?

**Comment by basrieter** [comment]
Ik moet even kijken of het mij gaat lukken om hier naar te kijken tijdens de live streams van de OS

**Comment by ltGuillaume** [comment]
Hmm...

> De NOS biedt tijdens de Olympische Spelen op NPO 1 en op de stream een olympisch totaalprogramma aan. Sommige onderdelen of wedstrijden laten we van begin tot einde live zien, maar er kan ook tussen de diverse sporten worden geschakeld.
> We hebben niet de rechten om naast het totaalprogramma extra livestreams aan te bieden.
https://nos.nl/tokyo2020/artikel/2390671-de-olympische-nacht-voor-deze-nederlanders-zet-je-de-wekker

**Comment by basrieter** [comment]
Please download https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/channel-1095.zip and use the "Install from zip" option in Kodi to install this version. 

The NOS channel should now have an extra option: Live TV which should contain all current and past live streams. Haven't tested it yet, because the Olympics are one too late. But feel free to test and let me know if it works as expected?

**Comment by basrieter** [comment]
Did anyone check this? @ltGuillaume @rrmvanderlinden ?

**Comment by ltGuillaume** [comment]
I'm having nothing but trouble with Kodi 19, so yes, I tried, but couldn't get it working. I just dove into all those idiotic Kodi 19 problems again and got it working.

So, I see a long, looooong list of titles under NOS.nl/Live, but (in this case) *all* of those streams are one and the same. It's just that the same stream changed names over time. Perhaps Retrospect could filter the list and only show the latest item/title of the same source stream?

![image](https://user-images.githubusercontent.com/4777345/127689374-d74f6ba0-b1f8-45f7-bc60-f815da36fc47.png)

**Comment by rrmvanderlinden** [comment]
> Did anyone check this? @ltGuillaume @rrmvanderlinden ?

Tried, but ended in phyton 3.0 error and haven't had time to solve this or figure out why it is working with Guillaume and gives me installation errors.

**Comment by ltGuillaume** [comment]
@rrmvanderlinden Still on Kodi 18 by any chance? Kodi 19+ uses Python 3, but you'll get a Python 3.0.0 dependency error in Kodi 18.

**Comment by basrieter** [comment]
Here is a Kodi Leia version: 
[plugin.video.retrospect-channel-1095.leia.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/6909361/plugin.video.retrospect-channel-1095.leia.zip)

> So, I see a long, looooong list of titles under NOS.nl/Live, but (in this case) all of those streams are one and the same. It's just that the same stream changed names over time. Perhaps Retrospect could filter the list and only show the latest item/title of the same source stream?

Right, so it's just the same stream over and over? So I can better just use the most recent stream and show that? Or are there moments that there are multiple live streams active?

**Comment by ltGuillaume** [comment]
There will be moments with multiple streams for sure.

**Comment by basrieter** [comment]
Ok, let me see what I can do here.

**Comment by ltGuillaume** [comment]
Great! You're up late, athletics fan perhaps? 😉

**Comment by rrmvanderlinden** [comment]
Up and running with windsurfing.

**Comment by ltGuillaume** [comment]
Crazy race, 3 disqualified, wow!

**Comment by basrieter** [comment]
I am not filtering the duplicates: 

[plugin.video.retrospect-channel-1095-2.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/6910977/plugin.video.retrospect-channel-1095-2.zip)

**Comment by basrieter** [comment]
I broke the "normal" items. Here is a fix for Leia: 

[plugin.video.retrospect-channel-1095-3.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/6910994/plugin.video.retrospect-channel-1095-3.zip)

**Comment by ltGuillaume** [comment]
![image](https://user-images.githubusercontent.com/4777345/127736678-48910c13-833f-44ae-9d0a-5a8e87849230.png)
The first item (Rutte) doesn't do anything (typical):
```
2021-07-31 12:14:36.793 T:3592  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--E81CADCD8FEF7450367FB2281E48D7395D7A2061B09261174DA7E72EA75C42A5&channel=channel.nos.nosnl-nosnl
2021-07-31 12:14:36.794 T:1960  NOTICE: Creating InputStream
2021-07-31 12:14:36.809 T:596   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 1085, in onPlayBackStarted
                                                play_data = get_playing_data()
                                              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.jellycon\resources\lib\play_utils.py", line 1055, in get_playing_data
                                                play_data = json.loads(play_data_string)
                                              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
2021-07-31 12:14:36.818 T:1960 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--E81CADCD8FEF7450367FB2281E48D7395D7A2061B09261174DA7E72EA75C42A5&channel=channel.nos.nosnl-nosnl|acceptencoding=gzip&seekable=0
2021-07-31 12:14:36.819 T:1960   ERROR: AddOnLog: InputStream Adaptive: Cannot download plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--E81CADCD8FEF7450367FB2281E48D7395D7A2061B09261174DA7E72EA75C42A5&channel=channel.nos.nosnl-nosnl
2021-07-31 12:14:36.819 T:1960   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--E81CADCD8FEF7450367FB2281E48D7395D7A2061B09261174DA7E72EA75C42A5&channel=channel.nos.nosnl-nosnl)
2021-07-31 12:14:36.819 T:1960   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--E81CADCD8FEF7450367FB2281E48D7395D7A2061B09261174DA7E72EA75C42A5&channel=channel.nos.nosnl-nosnl]
2021-07-31 12:14:36.819 T:1960  NOTICE: CVideoPlayer::OnExit()
2021-07-31 12:14:36.904 T:3592  NOTICE: CVideoPlayer::CloseFile()
2021-07-31 12:14:36.904 T:3592  NOTICE: VideoPlayer: waiting for threads to exit
2021-07-31 12:14:36.904 T:3592  NOTICE: VideoPlayer: finished waiting
```

All the others are the same stream. Note that, during the entire Olympics, there is only one stream.

Also note the dates (some are in the future, which is rather impressive for livestreams).

**Comment by basrieter** [comment]
This is just the list that NOS has. I am not planning on doing more with the data. The future streams, are just there so show what is coming up. If I were to only show a single stream (the current active one) it will not work if multiple live streams exists. 

The streams you see here, are those with unique urls.

**Comment by ltGuillaume** [comment]
Aah, that's clear. Thank you so much!!

**Comment by basrieter** [comment]
If it is acceptable like this, I will merge it and try to do a release tonight (before the Olympics are over).

**Comment by ltGuillaume** [comment]
Would be great!!

**Comment by ltGuillaume** [comment]
Thanks again, using it right now (damn, 4th).

**Comment by rrmvanderlinden** [comment]
Superb running on Leia, thanks!

**Comment by ltGuillaume** [comment]
A few minutes ago, there finally were three simultaneous streams (beach volley, athletics and one other), so I tried to start two of them. The main stream worked, but the beach volley stream didn't (log below). It did work from the website.

I'm not 100% sure this _should have_ worked, because shortly after, the second and third stream were gone from the website, too.
```
NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--C9C9A3210C634327F1DB6DCC694E1A9390E07F1296BE17F76CADDED4116E1193&channel=channel.nos.nosnl-nosnl
ERROR: Traceback (most recent call last):
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 48, in execute
                media_item = self.__channel.process_video_item(media_item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 480, in process_video_item
                return data_parser.Updater(item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\channels\channel.nos\nosnl\chn_nosnl.py", line 251, in update_json_video
                json_data = JsonHelper(data)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\helpers\jsonhelper.py", line 41, in __init__
                self.json = json.loads(self.data)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                return _default_decoder.decode(s)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                raise ValueError("No JSON object could be decoded")
            ValueError: No JSON object could be decoded
 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--1342AE293B845A0ECF10C7ABB8672E8EA7C7DB63B2F20D4BA5ADA4C8A80A47A7&channel=channel.nos.nosnl-nosnl]
ERROR: Traceback (most recent call last):
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 48, in execute
                media_item = self.__channel.process_video_item(media_item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 480, in process_video_item
                return data_parser.Updater(item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\channels\channel.nos\nosnl\chn_nosnl.py", line 251, in update_json_video
                json_data = JsonHelper(data)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\helpers\jsonhelper.py", line 41, in __init__
                self.json = json.loads(self.data)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                return _default_decoder.decode(s)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                raise ValueError("No JSON object could be decoded")
            ValueError: No JSON object could be decoded
 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--1342AE293B845A0ECF10C7ABB8672E8EA7C7DB63B2F20D4BA5ADA4C8A80A47A7&channel=channel.nos.nosnl-nosnl]
ERROR: Traceback (most recent call last):
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 48, in execute
                media_item = self.__channel.process_video_item(media_item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 480, in process_video_item
                return data_parser.Updater(item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\channels\channel.nos\nosnl\chn_nosnl.py", line 251, in update_json_video
                json_data = JsonHelper(data)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\helpers\jsonhelper.py", line 41, in __init__
                self.json = json.loads(self.data)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                return _default_decoder.decode(s)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                raise ValueError("No JSON object could be decoded")
            ValueError: No JSON object could be decoded
 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--1342AE293B845A0ECF10C7ABB8672E8EA7C7DB63B2F20D4BA5ADA4C8A80A47A7&channel=channel.nos.nosnl-nosnl]
ERROR: Traceback (most recent call last):
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 48, in execute
                media_item = self.__channel.process_video_item(media_item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 480, in process_video_item
                return data_parser.Updater(item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\channels\channel.nos\nosnl\chn_nosnl.py", line 251, in update_json_video
                json_data = JsonHelper(data)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\helpers\jsonhelper.py", line 41, in __init__
                self.json = json.loads(self.data)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                return _default_decoder.decode(s)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                raise ValueError("No JSON object could be decoded")
            ValueError: No JSON object could be decoded
 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--1342AE293B845A0ECF10C7ABB8672E8EA7C7DB63B2F20D4BA5ADA4C8A80A47A7&channel=channel.nos.nosnl-nosnl]
ERROR: Traceback (most recent call last):
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 48, in execute
                media_item = self.__channel.process_video_item(media_item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 480, in process_video_item
                return data_parser.Updater(item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\channels\channel.nos\nosnl\chn_nosnl.py", line 251, in update_json_video
                json_data = JsonHelper(data)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\helpers\jsonhelper.py", line 41, in __init__
                self.json = json.loads(self.data)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                return _default_decoder.decode(s)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                raise ValueError("No JSON object could be decoded")
            ValueError: No JSON object could be decoded
 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--1342AE293B845A0ECF10C7ABB8672E8EA7C7DB63B2F20D4BA5ADA4C8A80A47A7&channel=channel.nos.nosnl-nosnl]
ERROR: Traceback (most recent call last):
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\actions\videoaction.py", line 48, in execute
                media_item = self.__channel.process_video_item(media_item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\chn_class.py", line 480, in process_video_item
                return data_parser.Updater(item)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\channels\channel.nos\nosnl\chn_nosnl.py", line 251, in update_json_video
                json_data = JsonHelper(data)
              File "D:\Programs\Multimedia\Kodi\portable_data\addons\plugin.video.retrospect\resources\lib\helpers\jsonhelper.py", line 41, in __init__
                self.json = json.loads(self.data)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                return _default_decoder.decode(s)
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
              File "D:\Programs\Multimedia\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                raise ValueError("No JSON object could be decoded")
            ValueError: No JSON object could be decoded
 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=92BF426D57BCBDF4C5559E5B7DD18902B183B58E431976A5634BD2837C61FED8--1342AE293B845A0ECF10C7ABB8672E8EA7C7DB63B2F20D4BA5ADA4C8A80A47A7&channel=channel.nos.nosnl-nosnl]
NOTICE: Stopping player
NOTICE: Storing total System Uptime
NOTICE: Saving settings
NOTICE: Saving skin settings
NOTICE: Stopping all
NOTICE: ES: Stopping event server
NOTICE: CWebServer[8080]: Stopped
NOTICE: ES: UDP Event server stopped
NOTICE: Application stopped
NOTICE: XBApplicationEx: destroying...
NOTICE: unload skin
NOTICE: unload sections
NOTICE: XBApplicationEx: application stopped!
```
