### ISSUE TITLE
NPO start PLus items are not working..

### ISSUE THREAD

**Issue by powermarcel10** [retrospect-addon/plugin.video.retrospect#1291]
Hello,

I'm not able to watch npo start plus items. The normal items are playing fine but the items that require a plus subscription are not loading and I cannot even see them in the addon. By example, for flikken maastricht season 1 to 13, the items are not visible. In the NPO plus app on my phone, I'm able to play them. I am sure I entered the right cridentials in the addon settings..

Is this not working anymore?

**Comment by basrieter** [comment]
Did you configure the username and password for NPO via the `Channel Options -> Settings`?

**Comment by powermarcel10** [comment]
Yes I did.

**Comment by powermarcel10** [comment]
Here is some log rules:

2020-02-11 19:33:24.322 T:4208   ERROR: Traceback (most recent call last):
                                              File "C:\Users\power\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 798, in create_npo_item
                                                if self.__determine_date_time_for_npo_item(item, date_time, date_premium):
                                              File "C:\Users\power\AppData\Roaming\Kodi\addons\plugin.video.retrospect\channels\channel.nos\nos2010\chn_nos2010.py", line 1438, in __determine_date_time_for_npo_item
                                                if date_time[-2].lower() == "gisteren":
                                            IndexError: list index out of range
2020-02-11 19:33:34.003 T:11972   ERROR: Previous line repeats 199 times.
2020-02-11 19:33:34.003 T:11972   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=gAIoY3Jlc291cmNlcy5saWIubWVkaWFpdGVtCk1lZGlhSXRlbQpxAW9xAn1xAyhVDk1lZGlhSXRlbVBhcnRzcQRdVQlpc0Nsb2FrZWRxBYlVCGNvbXBsZXRlcQaJVQlhY3Rpb25VcmxxB05VDmlzRHJtUHJvdGVjdGVkcQiJVQRndWlkcQlVQDU1QjAxMTJGMThBM0U1RjcwNzkwNTU3NzZFRTVDNzlGRUE1RTg0NjEyNzJFMTlGOTVBMDIyMzI2NzAwRDFCNkJVCG1ldGFEYXRhcQp9VQV0aHVtYnELWD0AAABodHRwczovL2ltYWdlcy5wb21zLm9tcm9lcC5ubC9pbWFnZS9zMzIwL2MzMjB4MTgwLzEyODg2MzAuanBnVQZmYW5hcnRxDFhIAAAAcmVzb3VyY2U6Ly9yZXNvdXJjZS5pbWFnZXMucmV0cm9zcGVjdC9jaGFubmVsLm5vcy5ub3MyMDEwL25vc2ZhbmFydDQuanBncQ1VBmlzTGl2ZXEOiVUEaWNvbnEPWEYAAAByZXNvdXJjZTovL3Jlc291cmNlLmltYWdlcy5yZXRyb3NwZWN0L2NoYW5uZWwubm9zLm5vczIwMTAvbnBvbGFyZ2UucG5ncRBVBHR5cGVxEVUFdmlkZW9xElULSHR0cEhlYWRlcnNxE31xFFULZGVzY3JpcHRpb25xFVUAVQtpc0dlb0xvY2tlZHEWiVUVX01lZGlhSXRlbV9fdGltZXN0YW1wcRdjZGF0ZXRpbWUKZGF0ZXRpbWUKcRhVCgfdARgAAAAAAACFUnEZVRZfTWVkaWFJdGVtX19pbmZvTGFiZWxzcRp9VRBfTWVkaWFJdGVtX19kYXRlcRtVCjIwMTMtMDEtMjRVBmlzUGFpZHEciFUEbmFtZXEdWCgAAABUZWwgdG90IDkwIC0gIEFmbC4gMiAtIDI0IGphbiAyMDEzIDIzOjA2VQlkb250R3JvdXBxHolVA3VybHEfWAwAAABQT1dfMDA0ODA2MjdVBWl0ZW1zcSBdVQlndWlkVmFsdWVxIYogaxsNcCYjAlr5GS4nYYRe6p%2fH5W53VZAH9%2bWjGC8RsFV1Yi4%3d&channelcode=uzgjson&channel=chn_nos2010]
2020-02-11 19:33:39.423 T:11972   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrospect/?action=playvideo&pickle=gAIoY3Jlc291cmNlcy5saWIubWVkaWFpdGVtCk1lZGlhSXRlbQpxAW9xAn1xAyhVDk1lZGlhSXRlbVBhcnRzcQRdVQlpc0Nsb2FrZWRxBYlVCGNvbXBsZXRlcQaJVQlhY3Rpb25VcmxxB05VDmlzRHJtUHJvdGVjdGVkcQiJVQRndWlkcQlVQDAxNTkzODcxNEE2RjYzQkNEMEJBNDg0MUFFRjMwMDQ1MEIxMTBGQUYzNEFEMzVFMjI2NkZFNENCN0NCN0VBRERVCG1ldGFEYXRhcQp9VQV0aHVtYnELWD0AAABodHRwczovL2ltYWdlcy5wb21zLm9tcm9lcC5ubC9pbWFnZS9zMzIwL2MzMjB4MTgwLzEyODg2MzEuanBnVQZmYW5hcnRxDFhIAAAAcmVzb3VyY2U6Ly9yZXNvdXJjZS5pbWFnZXMucmV0cm9zcGVjdC9jaGFubmVsLm5vcy5ub3MyMDEwL25vc2ZhbmFydDQuanBncQ1VBmlzTGl2ZXEOiVUEaWNvbnEPWEYAAAByZXNvdXJjZTovL3Jlc291cmNlLmltYWdlcy5yZXRyb3NwZWN0L2NoYW5uZWwubm9zLm5vczIwMTAvbnBvbGFyZ2UucG5ncRBVBHR5cGVxEVUFdmlkZW9xElULSHR0cEhlYWRlcnNxE31xFFULZGVzY3JpcHRpb25xFVUAVQtpc0dlb0xvY2tlZHEWiVUVX01lZGlhSXRlbV9fdGltZXN0YW1wcRdjZGF0ZXRpbWUKZGF0ZXRpbWUKcRhVCgfdAR8AAAAAAACFUnEZVRZfTWVkaWFJdGVtX19pbmZvTGFiZWxzcRp9VRBfTWVkaWFJdGVtX19kYXRlcRtVCjIwMTMtMDEtMzFVBmlzUGFpZHEciFUEbmFtZXEdWDgAAABEZSBLdW5zdCB2YW4gaGV0IE1vZ2VsaWprZSAtICBBZmwuIDMgLSAzMSBqYW4gMjAxMyAyMzowMlUJZG9udEdyb3VwcR6JVQN1cmxxH1gMAAAAUE9XXzAwNDgwNjI4VQVpdGVtc3EgXVUJZ3VpZFZhbHVlcSGKIN3qt3zL5G8m4jWtNK8PEQtFAPOuQUi60Lxjb0pxOFkBdWIu&channelcode=uzgjson&channel=chn_nos2010]


Im getting the message "dit programma is niet (meer) beschikbaar. (15)"

**Comment by basrieter** [comment]
Please don't post parts of the log, but attach the full debug log.

**Comment by mvmsoft** [comment]
Ik heb het ook geprobeerd, op mijn raspberry met Kodi: geen probleem. Op de pc met Kodi 18.4 en RS 15.6 ook niet, maar ik moest wel mijn NPO Plus credentials goed invullen én een pin voorde kluis (vault) verzinnen. En Widevine moest er nog bij. Bij al dat geprobeer is er ook een log verstuurd: roduvupixe, die nergens op slaat.

**Comment by basrieter** [comment]
In de log staat constant "Incorrect Retrospect PIN specified":

```
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - Error running plugin
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - | Traceback (most recent call last):
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |   File "/root/.kodi/addons/plugin.video.retrospect/resources/lib/addon.py", line 62, in run_addon
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |     plugin.Plugin(sys.argv[0], sys.argv[2], sys.argv[1])
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |   File "/root/.kodi/addons/plugin.video.retrospect/resources/lib/plugin.py", line 153, in __init__
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |     v = Vault()
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |   File "/root/.kodi/addons/plugin.video.retrospect/resources/lib/vault.py", line 31, in __init__
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |     key = self.__get_application_key()  # type: bytes
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |   File "/root/.kodi/addons/plugin.video.retrospect/resources/lib/vault.py", line 245, in __get_application_key
20200211 20:20:51 - [CRITICAL] - addon.py             - 72   - |     raise RuntimeError("Incorrect Retrospect PIN specified")
```
Maar dat klopt met je verhaal. Ik denk echter dat je het filteren van betaalde items aan hebt staan:

![image](https://user-images.githubusercontent.com/1310443/74283899-0d445e80-4d23-11ea-88d1-00b79d176fb9.png)

Kan je dat eens nagaan? Als je de filtering uit hebt staan en je ziet ze nog niet, zou je dan een log kunnen posten nadat je navigeert naar de lijst van Flikken?

**Comment by powermarcel10** [comment]
Ik heb nog even lopen pielen met gebruikersnamen, wachtwoorden, kodi herstarten, instellingen, en ineens werkte het! Alles keurig fullHD. Super! Deze kan dus weer op slot. Sorry voor het loze alarm.

Wel vreemd: In bijvoorbeeld de map Flikken Maastricht staan alle afleveringen van alle seizoenen. De mappen met de seizoenen erbij zijn leeg. Het zou fijn als je per seizoen kan zoeken. Maar hoe dan ook, het werkt!

Bedankt voor de support heren.

**Comment by basrieter** [comment]
De seizoenen komen leeg uit de API van NPO, dus daar kan ik niks aan doen. Ik ga zelf altijd via de "full list/hele lijst" naar programma's en dan zie ik de seizoenen niet meer. Ik heb de naamgeving wat aangepast in de "verzamel" folders:

[retrospect-patch-20200212.004930.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4189169/retrospect-patch-20200212.004930.zip)

**Comment by powermarcel10** [comment]
> De seizoenen komen leeg uit de API van NPO, dus daar kan ik niks aan doen. Ik ga zelf altijd via de "full list/hele lijst" naar programma's en dan zie ik de seizoenen niet meer. Ik heb de naamgeving wat aangepast in de "verzamel" folders:
> 
> [retrospect-patch-20200212.004930.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/4189169/retrospect-patch-20200212.004930.zip)
> 
> Deze zip handmatig uitpakken en de originele bestanden vervangen.

Aaah top! Veel beter zo! Super bedankt!
