### ISSUE TITLE
Error when opening episodes list for kijk.nl show

### ISSUE THREAD

**Issue by Derkades** [retrospect-addon/plugin.video.retrospect#1442]
### To Reproduce

1. Open Retrospect
2. Select 'National' -> Kijk.nl -> C -> Chateau Meiland
3. Click 'Season 04'

### Debuglog

Error:
```
20201105 20:40:29 - [INFO ] - urihandler.py - 539 - GET resulted in '200 OK' (0:00:00.195783) for https://graph.kijk.nl/graphql?query=query%7Bprograms%28tvSeasonId%3A%22154012200198%22%2CprogramTypes%3AEPISODE%2Cskip%3A0%2Climit%3A100%29%7Bitems%7B__typename%2Ctitle%2Cdescription%2Cguid%2Cupdated%2CseriesTvSeasons%7Bid%7D%2CimageMedia%7Burl%2Clabel%7D%2Ctype%2Csources%7Btype%2Cdrm%2Cfile%7D%2Cseries%7Btitle%7D%2CseasonNumber%2CtvSeasonEpisodeNumber%2ClastPubDate%2Cduration%2CdisplayGenre%2Ctracks%7Btype%2Cfile%7D%7D%7D%7D 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - Plugin::Error Processing FolderList 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | Traceback (most recent call last): 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/actions/folderaction.py", line 53, in execute 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | media_items = self.__channel.process_folder_list(selected_item) 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 284, in process_folder_list 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | handler_result = data_parser.Creator(parser_result) 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.py", line 568, in create_api_typed_item 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | item = self.create_api_episode_type(result_set) 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.sbsnl/kijknl/chn_kijknl.py", line 691, in create_api_episode_type 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - | item.set_info_label("duration", int(result_set.get("duration", 0))) 
20201105 20:40:29 - [ERROR ] - folderaction.py - 118 - + TypeError: int() argument must be a string or a number, not 'NoneType'
```

Full debug log: https://derkad.es/retro.log

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 18.2 (LibreELEC 9.0.2)
- Retrospect version: 5.2.15

**Comment by basrieter** [comment]
Please provide a full DEBUG retrospect.log

**Comment by Derkades** [comment]
Added now, please let me know if you need more information/testing.

**Comment by basrieter** [comment]
Could you double check, it all seems to work here?

**Comment by Derkades** [comment]
I cannot reproduce anymore
