### ISSUE TITLE
URplay not playing

### ISSUE THREAD

**Issue by ChrisIse** [retrospect-addon/plugin.video.retrospect#1569]
### Describe the bug

Swedish URplay can't play episodes. The listings are fine though. Other channels work, like TV4.

## Expected Behavior

The episode sould play normally.

## Actual Behavior

Just an error message, can't start playing.

### To Reproduce

Retrospect -> National -> UR play ->Järnvägar och arkitektur -> Episode 8

### Debuglog

The **debug** retrospect.log can be found here:
```
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - Could not playback the url
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - | Traceback (most recent call last):
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - |   File "/home/osmc/.kodi/addons/plugin.video.retrospect/resources/lib/actions/videoaction.py", line 48, in execute
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - |     media_item = self.__channel.process_video_item(media_item)
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - |   File "/home/osmc/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 480, in process_video_item
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - |     return data_parser.Updater(item)
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - |   File "/home/osmc/.kodi/addons/plugin.video.retrospect/channels/channel.se/urplay/chn_urplay.py", line 567, in update_video_item
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - |     json_data = streams[0]
20211031 07:54:36 - [CRITICAL] - videoaction.py       - 108  - + IndexError: list index out of range
20211031 07:54:36 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.
20211031 07:55:57 - [INFO    ] - addon.py             - 35   - XOT Logger :: Appending Existing logFile
20211031 07:55:57 - [INFO    ] - urihandler.py        - 65   - Re-using existing UriHandler: UriHandler [id=1635662830, useCaching=Cache store [/home/osmc/.kodi/userdata/addon_data/plugin.video.retrospect/cache/www], ignoreSslErrors=False]
20211031 07:55:57 - [INFO    ] - plugin.py            - 34   - *********** Starting Retrospect add-on version 5.4.8 ***********
20211031 07:55:57 - [INFO    ] - chn_class.py         - 45   - Initializing channel (__init__): UR Play [channel.se.urplay=True, se=True, National, 9F0F57D6-B897-11E0-AF2E-92314924019B] (Order: #se.0002)
20211031 07:55:57 - [INFO    ] - plugin.py            - 103  - Loaded: UR Play
20211031 07:55:57 - [INFO    ] - urihandler.py        - 533  - Performing a GET for https://urplay.se/221059-jarnvagar-och-arkitektur-55-broadway-i-london
20211031 07:55:57 - [INFO    ] - urihandler.py        - 539  - GET resulted in '200 OK' (0:00:00.001185) for https://urplay.se/program/221059
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - Could not playback the url
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - | Traceback (most recent call last):
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - |   File "/home/osmc/.kodi/addons/plugin.video.retrospect/resources/lib/actions/videoaction.py", line 48, in execute
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - |     media_item = self.__channel.process_video_item(media_item)
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - |   File "/home/osmc/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 480, in process_video_item
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - |     return data_parser.Updater(item)
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - |   File "/home/osmc/.kodi/addons/plugin.video.retrospect/channels/channel.se/urplay/chn_urplay.py", line 567, in update_video_item
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - |     json_data = streams[0]
20211031 07:55:57 - [CRITICAL] - videoaction.py       - 108  - + IndexError: list index out of range
20211031 07:55:57 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: 19.1
- Retrospect version: 5.4.8

**Comment by basrieter** [comment]
Ok, can you attach a full debug retrospect.log?

**Comment by basrieter** [comment]
Please install this zip in Kodi Matrix and see if that fixes the issue: https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1569.zip

**Comment by ChrisIse** [comment]
That did the trick! Thanks, Bas, for fixing this so quickly.
