### ISSUE TITLE
Malformed NPO URL

### ISSUE THREAD

**Issue by Derkades** [retrospect-addon/plugin.video.retrospect#1611]
### Describe the bug

It looks like somehow it includes the protocol as part of the hostname (resulting in an unknown domain error) and the path starts with `//`
```
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - | During handling of the above exception, another exception occurred:
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - | Traceback (most recent call last):
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/actions/videoaction.py", line 48, in execute
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     media_item = self.__channel.process_video_item(media_item)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 480, in process_video_item
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     return data_parser.Updater(item)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py", line 1273, in update_video_item
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     return self.__update_video_item(item, whatson_id)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py", line 1400, in __update_video_item
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     self.__log_on(force_log_off=True)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py", line 267, in __log_on
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     UriHandler.open("https://id.npo.nl{}".format(redirect_url), no_cache=True)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 126, in open
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     return UriHandler.instance().open(uri, proxy, params, data, json,
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 431, in open
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     r = self.__requests(uri, proxy=proxy, params=params, data=data, json=json,
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 534, in __requests
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     r = s.get(uri, proxies=proxies, headers=headers,
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 555, in get
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     return self.request('GET', url, **kwargs)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     resp = self.send(prep, **send_kwargs)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     r = adapter.send(request, **kwargs)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 516, in send
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - |     raise ConnectionError(e, request=request)
20220126 17:48:04 - [CRITICAL] - videoaction.py       - 108  - + requests.exceptions.ConnectionError: HTTPSConnectionPool(host='id.npo.nlhttps', port=443): Max retries exceeded with url: //www.npostart.nl (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xd5211118>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

### To Reproduce

I tried to play a video in the "recents" section

### Debuglog

Doesn't seem relevant because the exception generated a backtrace, but I will provide this if needed.

### Your Environment
Used Operating system:

LibreELEC 10 on a Raspberry Pi 4

Used versions:
- Kodi version: Matrix
- Retrospect version: 5.5.2

**Comment by basrieter** [comment]
Could you please provide a full debug retrospect.log?

**Comment by Derkades** [comment]
Here it is: https://paste.kodi.tv/ezinuzamef.kodi

**Comment by basrieter** [comment]
Can you try clearing your cache from the Retrospect settings: 

![image](https://user-images.githubusercontent.com/1310443/151713858-d36af835-f744-4e4a-a413-8b476c347059.png)

**Comment by Derkades** [comment]
Clearing cache indeed resolved the issue
