### ISSUE TITLE
invalid Netscape format cookies file (cookiejar.dat)

### ISSUE THREAD

**Issue by diederikdehaas** [retrospect-addon/plugin.video.retrospect#1664]
### Describe the bug

This issue looks very much the same as #1643, but it happened to me twice in a very similar way.  
I run LibreELEC on a Rock64 and with the last 2 nightly builds I 'installed', Retrospect failed to start/run with the same cause:
```
kodi-rock64:~/.kodi/temp # tail -n30 kodi.log 
                                                   
2022-12-12 12:25:17.197 T:1203    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'http.cookiejar.LoadError'>
                                                   Error Contents: invalid Netscape format cookies file '/storage/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat': 'D'
                                                   Traceback (most recent call last):
                                                     File "/usr/lib/python3.11/http/cookiejar.py", line 2041, in _really_load
                                                   ValueError: not enough values to unpack (expected 7, got 1)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.retrospect/retroaddon.py", line 4, in <module>
                                                       addon.run_addon()
                                                     File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/addon.py", line 50, in run_addon
                                                       UriHandler.create_uri_handler(cache_dir=cache_dir,
                                                     File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 57, in create_uri_handler
                                                       handler = _RequestsHandler(
                                                                 ^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 320, in __init__
                                                       self.cookieJar.load()
                                                     File "/usr/lib/python3.11/http/cookiejar.py", line 1802, in load
                                                     File "/usr/lib/python3.11/http/cookiejar.py", line 2081, in _really_load
                                                   http.cookiejar.LoadError: invalid Netscape format cookies file '/storage/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat': 'D'
                                                   -->End of Python script error report<--
                                                   
2022-12-12 12:25:17.429 T:1202    error <general>: GetDirectory - Error getting plugin://plugin.video.retrospect/?action=listfolder&channel=channel.nos.nos2010-uzgjson&pickle=371B2686F2F4D962C2156897A749922B9E7EAD0B34A44E94A0D19E2ADFE27C29--8BED9D118A64D5CD10170EE8E1F89CE779E1D90CA01B521935CC4761F2047AB8
2022-12-12 12:25:17.438 T:1107    error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.retrospect/?action=listfolder&channel=channel.nos.nos2010-uzgjson&pickle=371B2686F2F4D962C2156897A749922B9E7EAD0B34A44E94A0D19E2ADFE27C29--8BED9D118A64D5CD10170EE8E1F89CE779E1D90CA01B521935CC4761F2047AB8) failed
2022-12-12 12:25:54.712 T:1107     info <general>: Samba is idle. Closing the remaining connections
2022-12-12 12:27:21.297 T:1107     info <general>: NFS is idle. Closing the remaining connections.
```

Both times removing the ``cookiejar.dat`` file (manually) fixed the issue. But as I had the same issue with both the latest nightly builds I tried and the same 'solution', this appears to be a consistent issue ... with a workaround.

It first occurred with ``LibreELEC-RK3328.arm-11.0-nightly-20221203-164bd92-rock64.img.gz`` and now again with ``LibreELEC-RK3328.arm-11.0-nightly-20221211-d41e7dc-rock64.img.gz``, but it did not happen with ``LibreELEC-RK3328.arm-11.0-nightly-20221117-bbab280-rock64.img.gz``

Installing a new image also means that the device gets rebooted, so I tried rebooting again, but that did not trigger the issue again. Unfortunately it did clear ``retrospect.log`` (and I only inspected it with ``vim``), so I can't paste the error from that file.

## Expected Behavior

Retrospect should just start 

## Actual Behavior

Retrospect failed to start

## Possible Fix

It could be that the newest components (like python 3.11) could trigger this issue or what were previously warnings are now considered errors, which is not uncommon if (now) deprecated functions/modules are being used.

### To Reproduce

1. Put a new nightly build in ~/.update/
2. Reboot
3. Try to start Retrospect

### Debuglog

The **debug** retrospect.log can be found here:
As described above, by rebooting the device I lost the error info from retrospect.log, so I can't provide that.
IIRC it did not provide (significant) extra info as what is provided above.

### Your Environment
Used Operating system:

LibreELEC on Pine64's Rock64

Used versions:
- Kodi version: LibreELEC nightly-20221211-d41e7dc
- Retrospect version: 5.5.11+matrix.1

**Comment by basrieter** [comment]
Most likely corrupted. From the Retrospect settings please use the clear cache option.

**Comment by diederikdehaas** [comment]
Would that do more then ``rm cookiejar.dat``? I have already done that and Retrospect is now working again.  
But I also did that a little over a week ago which means it got recreated and corrupted in the meantime? It could be ofc, but I suspect there's more to it after it happened again so shortly after it.

**Comment by diederikdehaas** [comment]
It's an eMMC card and if it has problems, I would expect more/other issues. But it *could* be.  

I've backed up the ``cookiejar.dat`` file and now I also know it's just a simple text file, so the next time this happens, I can properly inspect things.
LE has an interesting update coming up (kernel 6.1), so I'm waiting for a new image to be build and then I'll update again.

**Comment by basrieter** [comment]
Ok, so that would make no sense then with eMMC. Let me know if it happens again and what you find out.

**Comment by diederikdehaas** [comment]
Did another update and the issue is back!
```
kodi-rock64:~/.kodi/userdata/addon_data/plugin.video.retrospect # cat retrospect.log 
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - Error running plugin
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - | Traceback (most recent call last):
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |   File "/usr/lib/python3.11/http/cookiejar.py", line 2041, in _really_load
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - | ValueError: not enough values to unpack (expected 7, got 1)
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - | During handling of the above exception, another exception occurred:
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - | Traceback (most recent call last):
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/addon.py", line 50, in run_addon
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |     UriHandler.create_uri_handler(cache_dir=cache_dir,
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 57, in create_uri_handler
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |     handler = _RequestsHandler(
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |               ^^^^^^^^^^^^^^^^^
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/urihandler.py", line 320, in __init__
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |     self.cookieJar.load()
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |   File "/usr/lib/python3.11/http/cookiejar.py", line 1802, in load
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - |   File "/usr/lib/python3.11/http/cookiejar.py", line 2081, in _really_load
20221221 14:54:16 - [CRITICAL] - addon.py             - 70   - + http.cookiejar.LoadError: invalid Netscape format cookies file '/storage/.kodi/userdata/addon_data/plugin.video.retrospect/cookiejar.dat': 'D'
20221221 14:54:16 - [INFO    ] - addon.py             - 71   - Retrospect :: Flushing and closing logfile.
```
But now with the backed-up ``cookiejar.dat`` file, we can compare them:
```
kodi-rock64:~/.kodi/userdata/addon_data/plugin.video.retrospect # cat cookiejar.dat 
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.

.www.uitzendinggemist.nl        TRUE    /       FALSE   4102444555      site_cookie_consent     yes
.www.uitzendinggemist.nl        TRUE    /       FALSE   4102444555      npo_cc  tmp
.npo.nl TRUE    /       FALSE   4102444555      site_cookie_consent     yes
.npo.nl TRUE    /       FALSE   4102444555      npo_cc  30
.npostart.nl    TRUE    /       FALSE   4102444555      site_cookie_consent     yes
.npostart.nl    TRUE    /       FALSE   4102444555      npo_cc  30
www.npostart.nl FALSE   /       TRUE    1673645987      XSRF-TOKEN      eyJpdiI6IjBzNGxRUkNzb3JvM200ZFdDNFQ1OGc9PSIsInZhbHVlIjoiNVpYdVFsSUlidWI0T1FGOWdCdmgrNDRFdzltUVwveWdpVW03enIyWlN4ZzlpMSsxaWNaXC9Pbm1DRmlmYklJQ1g3IiwibWFjIjoiOGQ3OGY5OTNjZDdjYjFhNDE1Zjk1YTIzNDdlZmQ2OTYxNDZkZTY1NGNkMDNlNzE5MzFlZWZmOTUxZjIyOTk2OSJ9
www.npostart.nl FALSE   /       TRUE    1673645987      npo_session     eyJpdiI6InRnclVBcld3eVpcL041MDJlVjlMbm9BPT0iLCJ2YWx1ZSI6InBrbnFzVVVGZXExK0xyOXV4em5CZ0VCNWJXU2VSdTdleWVISjZBbDNXOGVpQzNBYmR0YW1DeWhTMEMzbzRGWGEiLCJtYWMiOiJiZDVlYjliODgyNGFiZGNiZTc2ZWM4OWE2MDc1MTBkNDBjMDlkZjlhMTgzODg2OTBhMDg1NzZkZTgxNzIzNDczIn0%3D
D
```
```
kodi-rock64:~/.kodi/userdata/addon_data/plugin.video.retrospect # cat ~/backup/cookiejar.dat 
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This is a generated file!  Do not edit.

.www.uitzendinggemist.nl        TRUE    /       FALSE   4102444555      site_cookie_consent     yes
.www.uitzendinggemist.nl        TRUE    /       FALSE   4102444555      npo_cc  tmp
.npo.nl TRUE    /       FALSE   4102444555      site_cookie_consent     yes
.npo.nl TRUE    /       FALSE   4102444555      npo_cc  30
.npostart.nl    TRUE    /       FALSE   4102444555      site_cookie_consent     yes
.npostart.nl    TRUE    /       FALSE   4102444555      npo_cc  30
```

And it turns out the last line with just ``D`` is the problem. When I delete that line, Retrospect does start up :-)

**Comment by basrieter** [comment]
Please see #1666

**Comment by diederikdehaas** [comment]
I'll may try to figure out the root cause, but I'm quite sure the workaround would work, thanks :+1: 

No need to keep this issue open for that. Even more as there is also another one.
