### ISSUE TITLE
Playback of NPO shows fails

### ISSUE THREAD

**Issue by mvgorcum** [retrospect-addon/plugin.video.retrospect#1681]
### Describe the bug
NPO Start playback does not start.

## Expected Behavior
Select show episode, start it, and it starts playing.

## Actual Behavior
Retrospect gives back 'cannot start playback'

### To Reproduce

1. Select episode to watch
2. Playback doesn't happen.
3.

### Debuglog
```
LibreELEC:~/.kodi/userdata/addon_data/plugin.video.retrospect # tail -n 22 retrospect.log 
20230301 22:40:45 - [INFO    ] - urihandler.py        - 559  - POST resulted in '200 OK' (0:00:00.149743) for https://www.npostart.nl/player/VPWON_1348941
20230301 22:40:45 - [INFO    ] - urihandler.py        - 554  - Performing a GET for https://start-player.npo.nl/video/VPWON_1348941/streams?profile=dash-widevine&quality=npo&tokenId=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzbWFydHRhZyI6eyJzaXRlSWQiOiI0In0sImhhc1N1YnNjcmlwdGlvbiI6IiIsImhhc1ByZW1pdW1TdWJzY3JpcHRpb24iOiIiLCJlbGVtZW50SWQiOiJwbGF5ZXItVlBXT05fMTM0ODk0MSIsIm1lZGlhSWQiOiJWUFdPTl8xMzQ4OTQxIiwidG9wc3BpbiI6eyJwYXJ0eUlkIjoiIiwicHJvZmlsZUlkIjoiIn0sImhhc1NldHRpbmdzIjoiMSIsImhhc0FkQ29uc2VudCI6IjEiLCJzaGFyZSI6IjEiLCJlbmFibGVUaHVtYm5haWxTY3JvbGwiOiIxIiwibWFya2VycyI6IjEiLCJyZWNvbW1lbmRhdGlvbnMiOiIyNSIsImVuZHNjcmVlbiI6eyJoaWRlX2Zvcl90eXBlcyI6WyJmcmFnbWVudCIsImNsaXAiLCJ0cmFpbGVyIl19LCJzdHlsZVZlcnNpb24iOiIyIiwibW9yZUJ1dHRvbiI6IjEiLCJlbmRPZkNvbnRlbnRUZXh0IjoiMSIsImNocm9tZWNhc3QiOnsiZW5hYmxlZCI6IjEifSwic3R5bGluZyI6eyJ0aXRsZSI6eyJkaXNwbGF5Ijoibm9uZSJ9fSwicGFnZVVybCI6IiIsInN0ZXJSZWZlcnJhbFVybCI6IiIsInN0ZXJTaXRlSWQiOiJucG9zdGFydCIsInN0eWxlc2hlZXQiOiJodHRwczpcL1wvd3d3Lm5wb3N0YXJ0Lm5sXC9zdHlsZXNcL3BsYXllci5jc3MiLCJjb252aXZhIjp7ImVuYWJsZWQiOiIxIiwiYnJvYWRjYXN0ZXJOYW1lIjoiTlBPU1RBUlQifSwiaWF0IjoxNjc3NzA2ODQ1LCJuYmYiOjE2Nzc3MDY4NDUsImV4cCI6MTY3NzczNTY0NSwiY29uc3VtZXJJZCI6bnVsbCwiaXNQbGF5bGlzdCI6ZmFsc2UsInJlZmVycmVyVXJsIjpudWxsLCJza2lwQ2F0YWxvZyI6MCwibm9BZHMiOjAsImlzcyI6ImV5SnBkaUk2SW1sQlZWWTRSMmQxZGtneFoxYzBaWHBOZG5sNVJFRTlQU0lzSW5aaGJIVmxJam9pYm5OV1ZGRllPV3B3ZW1SbVozTlRXSFZ0V0Zka01HVmphRTk1YTBwWk5rVlNZa2hOUmpCME1HNVRjazFQZDFFek1VSllkWGRNVkZsaGRqWkdla1JTYkNJc0ltMWhZeUk2SWpZMU5EazNOelExWldZd056VmpZVFk0WlRRNE1XTXdOalV5WmpRM09URXlaRFU1TlRZNE0yWTJNbVJpWVRJek56RXdOR1EzTldaa1lqTmhaVEZsTmpjaWZRPT0ifQ.xozBEsfqWGqkK1L8DBd1vjsrxibyws_QxX6y-5FTkJY&streamType=broadcast&mobile=0&isChromecast=0
20230301 22:40:45 - [ERROR   ] - urihandler.py        - 562  - GET failed with '405 Method Not Allowed' (0:00:00.101753) for https://start-player.npo.nl/video/VPWON_1348941/streams?profile=dash-widevine&quality=npo&tokenId=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzbWFydHRhZyI6eyJzaXRlSWQiOiI0In0sImhhc1N1YnNjcmlwdGlvbiI6IiIsImhhc1ByZW1pdW1TdWJzY3JpcHRpb24iOiIiLCJlbGVtZW50SWQiOiJwbGF5ZXItVlBXT05fMTM0ODk0MSIsIm1lZGlhSWQiOiJWUFdPTl8xMzQ4OTQxIiwidG9wc3BpbiI6eyJwYXJ0eUlkIjoiIiwicHJvZmlsZUlkIjoiIn0sImhhc1NldHRpbmdzIjoiMSIsImhhc0FkQ29uc2VudCI6IjEiLCJzaGFyZSI6IjEiLCJlbmFibGVUaHVtYm5haWxTY3JvbGwiOiIxIiwibWFya2VycyI6IjEiLCJyZWNvbW1lbmRhdGlvbnMiOiIyNSIsImVuZHNjcmVlbiI6eyJoaWRlX2Zvcl90eXBlcyI6WyJmcmFnbWVudCIsImNsaXAiLCJ0cmFpbGVyIl19LCJzdHlsZVZlcnNpb24iOiIyIiwibW9yZUJ1dHRvbiI6IjEiLCJlbmRPZkNvbnRlbnRUZXh0IjoiMSIsImNocm9tZWNhc3QiOnsiZW5hYmxlZCI6IjEifSwic3R5bGluZyI6eyJ0aXRsZSI6eyJkaXNwbGF5Ijoibm9uZSJ9fSwicGFnZVVybCI6IiIsInN0ZXJSZWZlcnJhbFVybCI6IiIsInN0ZXJTaXRlSWQiOiJucG9zdGFydCIsInN0eWxlc2hlZXQiOiJodHRwczpcL1wvd3d3Lm5wb3N0YXJ0Lm5sXC9zdHlsZXNcL3BsYXllci5jc3MiLCJjb252aXZhIjp7ImVuYWJsZWQiOiIxIiwiYnJvYWRjYXN0ZXJOYW1lIjoiTlBPU1RBUlQifSwiaWF0IjoxNjc3NzA2ODQ1LCJuYmYiOjE2Nzc3MDY4NDUsImV4cCI6MTY3NzczNTY0NSwiY29uc3VtZXJJZCI6bnVsbCwiaXNQbGF5bGlzdCI6ZmFsc2UsInJlZmVycmVyVXJsIjpudWxsLCJza2lwQ2F0YWxvZyI6MCwibm9BZHMiOjAsImlzcyI6ImV5SnBkaUk2SW1sQlZWWTRSMmQxZGtneFoxYzBaWHBOZG5sNVJFRTlQU0lzSW5aaGJIVmxJam9pYm5OV1ZGRllPV3B3ZW1SbVozTlRXSFZ0V0Zka01HVmphRTk1YTBwWk5rVlNZa2hOUmpCME1HNVRjazFQZDFFek1VSllkWGRNVkZsaGRqWkdla1JTYkNJc0ltMWhZeUk2SWpZMU5EazNOelExWldZd056VmpZVFk0WlRRNE1XTXdOalV5WmpRM09URXlaRFU1TlRZNE0yWTJNbVJpWVRJek56RXdOR1EzTldaa1lqTmhaVEZsTmpjaWZRPT0ifQ.xozBEsfqWGqkK1L8DBd1vjsrxibyws_QxX6y-5FTkJY&streamType=broadcast&mobile=0&isChromecast=0
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - Could not playback the url
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - | Traceback (most recent call last):
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/actions/videoaction.py", line 48, in execute
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |     media_item = self.__channel.process_video_item(media_item)
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 480, in process_video_item
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |     return data_parser.Updater(item)
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py", line 1255, in update_video_item
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |     return self.__update_video_item(item, whatson_id)
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.nos/nos2010/chn_nos2010.py", line 1388, in __update_video_item
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |     error = NpoStream.add_mpd_stream_from_npo(None, episode_id, item, live=item.isLive)
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/streams/npostream.py", line 96, in add_mpd_stream_from_npo
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |     stream_data = JsonHelper(data)
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/helpers/jsonhelper.py", line 41, in __init__
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |     self.json = json.loads(self.data)
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - |   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
20230301 22:40:45 - [CRITICAL] - videoaction.py       - 108  - + json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
20230301 22:40:45 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.
```

### Your Environment
Used Operating system:
Libreelec 10.0.3 on x86 (intel NUC)

Used versions:
- Kodi version: 19
- Retrospect version:  5.5.13

**Comment by basrieter** [comment]
Please search (it was even pinned in the issue list): #1679

**Comment by mvgorcum** [comment]
Apologies! I did actually look through the issues list, but for some reason completely skipped over the pinned issues :( Sorry.
