### ISSUE TITLE
Recurring Error Issues with GoPlay/Vier Content

### ISSUE THREAD

**Issue by pejeio** [retrospect-addon/plugin.video.retrospect#1846]
Hi,

I’ve been encountering frequent errors when trying to watch several shows on **GoPlay/Vier**. Below are some log snippets that might assist in troubleshooting.

Please let me know if you need further details or additional information.

```
20241011 21:12:26 - [INFO    ] - plugin.py            - 34   - *********** Starting Retrospect add-on version 5.7.18 ***********
20241011 21:12:26 - [INFO    ] - chn_class.py         - 41   - Initializing channel (__init__): Vier [channel.be.vier=True, be=True, National, 50E04907-8983-4552-A775-E70F3D91FB99] (Order: #be.0004)
20241011 21:12:26 - [INFO    ] - plugin.py            - 103  - Loaded: Vier
20241011 21:12:26 - [INFO    ] - folderaction.py      - 44   - Plugin::process_folder_list Doing process_folder_list
20241011 21:12:26 - [INFO    ] - urihandler.py        - 547  - Performing a GET for https://www.goplay.be/gert-late-night
20241011 21:12:26 - [INFO    ] - urihandler.py        - 552  - GET resulted in '200 OK' (0:00:00.000912) for https://www.goplay.be/gert-late-night
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - Plugin::Error Processing FolderList
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - | Traceback (most recent call last):
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |   File "/Users/myuser/Library/Application Support/Kodi/addons/plugin.video.retrospect/resources/lib/actions/folderaction.py", line 59, in execute
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |     media_items = self.__channel.process_folder_list(selected_item)
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |   File "/Users/myuser/Library/Application Support/Kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 268, in process_folder_list
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |     (handler_data, pre_items) = data_parser.PreProcessor(data)
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |   File "/Users/myuser/Library/Application Support/Kodi/addons/plugin.video.retrospect/channels/channel.be/vier/chn_vier.py", line 33, in __call__
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |     nextjs_data = Regexer.do_regex(nextjs_regex, data)[0]
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
20241011 21:12:26 - [ERROR   ] - folderaction.py      - 138  - + IndexError: list index out of range
20241011 21:12:26 - [INFO    ] - addon.py             - 65   - Retrospect :: Flushing and closing logfile.
20241011 21:12:26 - [INFO    ] - addon.py             - 32   - XOT Logger :: Appending Existing logFile
```

<img width="561" alt="Screenshot 2024-10-11 at 21 10 32" src="https://github.com/user-attachments/assets/7076e4d8-d437-4eba-bc82-9c0d97e044eb">

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version: `21.0`
- Retrospect version: `5.7.18`

**Comment by basrieter** [comment]
I see, let me fix that

**Comment by basrieter** [comment]
Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1846.zip and let me know.

**Comment by pejeio** [comment]
> Please install https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1846.zip and let me know.

Thank you so much @basrieter! It works as expected.

**Comment by pejeio** [comment]
Hi @basrieter , it looks like we’re running into the same issue again. 🙁
Logs:

```
2024-10-12 20:15:40.178 T:4973252    info <general>: Retrospect :: Additional logging can be found in '/Users/myyser/Library/Application Support/Kodi/userdata/addon_data/plugin.video.retrospect/retrospect.log'
2024-10-12 20:15:40.201 T:4973252 critical <general>: Traceback (most recent call last):
                                                     File "/Users/myyser/Library/Application Support/Kodi/addons/plugin.video.retrospect/resources/lib/actions/folderaction.py", line 59, in execute
                                                       media_items = self.__channel.process_folder_list(selected_item)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/myyser/Library/Application Support/Kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 268, in process_folder_list
                                                       (handler_data, pre_items) = data_parser.PreProcessor(data)
                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/myyser/Library/Application Support/Kodi/addons/plugin.video.retrospect/channels/channel.be/vier/chn_vier.py", line 40, in __call__
                                                       nextjs_json = JsonHelper(nextjs_data)
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Users/myyser/Library/Application Support/Kodi/addons/plugin.video.retrospect/resources/lib/helpers/jsonhelper.py", line 39, in __init__
                                                       self.json = json.loads(self.data)
                                                                   ^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.11/json/__init__.py", line 346, in loads
                                                       return _default_decoder.decode(s)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/Applications/Kodi.app/Contents/Libraries/lib/python3.11/json/decoder.py", line 340, in decode
                                                       raise JSONDecodeError("Extra data", s, end)
                                                   json.decoder.JSONDecodeError: Extra data: line 1 column 516151 (char 516150)
                                                   
2024-10-12 20:15:40.202 T:4974065   error <general>: GetDirectory - Error getting plugin://plugin.video.retrospect/?action=listfolder&channel=channel.be.vier&pickle=50E04907-8983-4552-A775-E70F3D91FB99--C776CFFD14AE5F0DE684F7C1EF81B659DCD65B669DEEBAEB2E674FDA0FE4F891
2024-10-12 20:15:40.203 T:4973071   error <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.retrospect/?action=listfolder&channel=channel.be.vier&pickle=50E04907-8983-4552-A775-E70F3D91FB99--C776CFFD14AE5F0DE684F7C1EF81B659DCD65B669DEEBAEB2E674FDA0FE4F891) failed
2024-10-12 20:15:40.329 T:4974067    info <general>: Retrospect :: Additional logging can be found in '/Users/myyser/Library/Application Support/Kodi/userdata/addon_data/plugin.video.retrospect/retrospect.log'
2024-10-12 20:15:40.469 T:4974067 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
```

**Comment by basrieter** [comment]
Can you provide a full debug Retrospect.log?

**Comment by pejeio** [comment]
> Can you provide a full debug Retrospect.log?

Sure, there you go:
[retrospect.log](https://github.com/user-attachments/files/17355978/retrospect.log)

**Comment by basrieter** [comment]
> > Can you provide a full debug Retrospect.log?
> 
> Sure, there you go: [retrospect.log](https://github.com/user-attachments/files/17355978/retrospect.log)

Sorry, this is not a debug log. Change the level via the Retrospect settings to debug, reproduce and upload a new log.

**Comment by pejeio** [comment]
Hey, sorry about that! Here’s the full log.
[retrospect.log](https://github.com/user-attachments/files/17356338/retrospect.log)

One thing to point out: it seems like the availability of shows is inconsistent. For example, two hours ago, “Gert Late Night” wasn’t working, but now it opens and lets me select an episode without any issues. I’m using the exact same version: `bug-1846.zip` (with auto-update turned off). Pretty strange, right?

Let me know if you need more info!

**Comment by basrieter** [comment]
Please try https://github.com/retrospect-addon/plugin.video.retrospect/archive/refs/heads/bug-1846.zip again (redownload and install). Should be fixed! 

@pejeio Could you also check if your initial issue is still fixed.

**Comment by pejeio** [comment]
I’m able to open any show now, including the one I had trouble with initially! Fingers crossed it stays that way 🤞 Huge thanks, you’re a legend! 🙌

**Comment by basrieter** [comment]
Fixed in https://github.com/retrospect-addon/plugin.video.retrospect/releases/tag/v5.7.19: Kodi will update the add-on as soon as mirrors have synced.
